version: "3"

services:
  ansible_dev_container:
    # build: .
    image: quay.io/ansible/ansible-runner
    volumes:
      - .:/home/runner
    command: "sleep infinity"
    working_dir: /home/runner

volumes:
  project_data: