- name: playbook to test my env
  hosts: localhost

  tasks:
    - name: debug hello
      debug:
        msg: "{{ ansible_facts }}"

    - name: debug hello
      debug:
        msg: "Hola desde el Contenedor {{ ansible_facts.hostname }}"

# command
# ansible-playbook test_play.yml -v